/**********************************************************************************************************************
 * \file Cpu2_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"

#include "XinDongLib/Interrupts.h"
#include "XinDongLib/Intercore.h"
#include "XinDongLib/Bluetooth.h"
#include "XinDongLib/Display.h"
#include "XinDongLib/Encoder.h"
#include "XinDongLib/IMU.h"
#include "XinDongLib/IO.h"
#include "XinDongLib/Movements.h"
#include "XinDongLib/Serial.h"
#include "XinDongLib/Ultrasonic.h"
#include "XinDongLib/Time.h"
#include "XinDongLib/ADC.h"
#include "XinDongLib/CV.h"

// PID control parameters
#define TURN_KP  0.003f   // Steering P parameter
#define TURN_KD  0.001f   // Steering D parameter
#define SPEED_NORMAL  0.3f    // Normal speed (30%)
#define SPEED_TURN   0.25f    // Turn speed (25%)

// Straight/Turn detection thresholds
#define STRAIGHT_ERROR_THRESHOLD 10    // Midline error threshold
#define TURN_COUNT_THRESHOLD    5      // Consecutive detection count threshold

// Line following variables
static sint16 last_error = 0;       // Previous error
static uint8 turn_count = 0;        // Consecutive turn counter
static float current_speed = SPEED_NORMAL;  // Current speed

extern IfxCpu_syncEvent g_cpuSyncEvent;

void core2_main(void) {
    IfxCpu_enableInterrupts();
	/* !!WATCHDOG2 IS DISABLED HERE!!
	 * Enable the watchdog and service it periodically if it is required
	 */
	IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());

	/* Wait for CPU sync event */
	IfxCpu_emitEvent(&g_cpuSyncEvent);
	IfxCpu_waitEvent(&g_cpuSyncEvent, 1);

	// wait for signal to begin initialization
	while (Intercore_InitAllowed() == 0)
		;

	// initialize any module needed
	Serial_Init();
	Bluetooth_Init();
	ADC_Init();
	Ultrasonic_Init();
	OLED_Init();
	MPU6050_Init();
	Encoder_Init();
	Servo_Init();
	Motor_Init();
	PID_Init(0.1, 0.0, 0.0);

	// wait for other cores to finish initialization
	Intercore_CPU2_Ready();
	while (Intercore_ReadyToGo() == 0)
		;

	// Set servo center calibration (if needed)
    Servo_SetCenter(0.0f);
    
	// main loop
	while (1) {
		// Running indicator
		IO_LED_Toggle(3);
		Time_Delay_us(100000);
	}
}

/* list out all ISR for CPU2 */

void Periodic_1s_ISR(void) {
	;
}

void Periodic_100ms_ISR(void) {
	;
}

void Periodic_10ms_ISR(void) {
	CV_Result_t cv_result;
    float servo_output;
    
    // 1. Get image processing result
    cv_result = CV_ProcessImage();
    
    if(cv_result.valid) {
        // 2. Detect straight/turn section
        if(abs(cv_result.error) > STRAIGHT_ERROR_THRESHOLD) {
            // Possible turn detected
            turn_count++;
            if(turn_count > TURN_COUNT_THRESHOLD) {
                current_speed = SPEED_TURN;  // Reduce speed for turn
            }
        } else {
            // Straight section
            turn_count = 0;
            current_speed = SPEED_NORMAL;  // Resume normal speed
        }
        
        // 3. Calculate servo output (PD control)
        servo_output = TURN_KP * cv_result.error + 
                      TURN_KD * (cv_result.error - last_error);
                      
        // 4. Update control outputs
        Motor_Set(current_speed);
        Servo_Set(servo_output);
        
        // 5. Save previous error
        last_error = cv_result.error;
    }
}

void Periodic_PID_ISR(void) {
	;
}

void SWINT_User0_ISR(void) {
	;
}

void SWINT_User1_ISR(void) {
	;
}

void SWINT_User2_ISR(void) {
	;
}

void SWINT_User3_ISR(void) {
	;
}

void Serial_Received(uint8 *dataptr, uint32 length, uint8 tag) {
	switch (tag) {
	case 1:

		break;
	default:
		;
	}
}

void Bluetooth_Received(uint8 *dataptr, uint32 length, uint8 tag) {
	switch (tag) {
	case 1:

		break;
	default:
		;
	}
}
